#!/bin/bash

# notebook - A script to make notes inside terminal
# Licensed under the MIT License
# Copyright (c) 2020 Rekechynsky Dmytro aka DMENT
#
# NOTE: notebook saves notes on the principle
# "one note - one line", so consider the terms
# "note" and "line" the same.



##### Initialization

# Files are saved in the folder ~/.notebook_files
# Now, '@' path is refered to '~./notebook_files'
#
# Notes are saved in the file @/local_notes
# Backup is located in the file @/local_notes_backup
# @/local_notes_temp is temporary file, which is
# used for performing operations of deleting lines.

filename=~/.notebook_files/local_notes;
filename_temp=~/.notebook_files/local_notes_temp;
filename_backup=~/.notebook_files/local_notes_backup;

# In order to avoid performing operations at non-existent
# files it's good to create the files.

if ! [[ -d ~/.notebook_files ]];
then
    mkdir ~/.notebook_files;
fi

if ! [[ -f $filename ]];
then
    touch $filename;
fi

# If temporary file exists, remove it.
# Even it is deleted every time after performing some
# operations, it helps to avoid corruptions.

if [[ -f $filename_temp ]];
then
    rm $filename_temp;
fi



##### Colors


# notebook has feature to paint notes with
# different colors. This feature is provided
# easily thanks to regular expressions (REGEXP).

# It's not "white color" REGEXP, but "clear
# all formats were set before"

white="\\e[0m";

bold="\\e[1m";
red="\\e[31m";
green="\\e[32m";
yellow="\\e[33m";
blue="\\e[34m";
magenta="\\e[35m";
cyan="\\e[36m";



##### Variables


# Holds color value. The default is white.

color=$white;

# The count of all the notes.

line_count=$( wc -l $filename | awk '{ print $1 }' );

# Detected terminal

terminal=;



##### Functions


# write_notes() adds a note to file in the format:
# LINE_NUMBER. REGEXP_SET_COLOR NOTE REGEXP_CLEAR_FORMAT
# But you can't add empty note.

write_notes()
{
    note="$1";
    if [[ -n $note ]];
    then
        number=$( printf "$line_count + 1\\n" | bc );
        printf "$number. $color$note$white\\n" >> $filename;
    else
        printf "You should add non-empty note\\n";
        exit 1;
    fi
}

# choose_color() converts the verbal expression of
# color into REGEXP.
# If you set color, which is not in the list, an error
# message appears.

choose_color()
{
    case $1 in

        'white')
            color=$bold;
        ;;
        'red')
            color=$red;
        ;;
        'green')
            color=$green;
        ;;
        'yellow')
            color=$yellow;
        ;;
        'blue')
            color=$blue;
        ;;
        'magenta')
            color=$magenta;
        ;;
        'cyan')
            color=$cyan;
        ;;
        *)
            printf "Possible colors: white, red, green, yellow, blue, magenta, cyan\\n";
            exit 1;
        ;;
esac
}

# show_notes() shows all the notes, saved to @/local_notes
# If @/local_notes is empty, the appropriate message appears.

show_notes()
{
    if [[ $line_count == "0" ]];
    then
        printf "There are no notes.\\n"
    else
        cat $filename;
    fi
}

# clear_notes() clears the file @/local_notes
# by rewriting text into empty string.

clear_notes()
{
    printf '' > $filename;
}


# correct_number_checking() is the helping
# function for remove_line()
# It checks the arguments for:
# - being the positive integer, actually;
# - being the existent note number (not greater, than
#   count of lines in the file)

correct_number_checking()
{
    number_mask='^[0-9]+$';
    if ! [[ $1 =~ $number_mask ]];
    then
        printf "Is \\'$to_check\\' an positive integer?\\n";
        exit 1;
    elif [ $1 -gt "$line_count" ];
    then
        printf "This line doesn't exist.\\n";
        exit 1;
    fi
}

# remove_line() removes the line (or lines) from the file in
# a such way:
# 1) Check $to_remove to be correct argument
# 2) Create temporary file
# 3) Coprying the lines from original to temporary file
#    through iteration (from the first to the line before line
#    that must be removed).
# 4) Continue copying lines from the new point.
#    The new point is:
#    - line after $remove_till
#    - or, if $remove_till is empty, line after $to_remove
# 5) Delete original file, rename temporary file as the original.

remove_line()
{
    to_remove=$1;
    remove_till=$2;
    correct_number_checking $to_remove;

    touch $filename_temp;

    i=1;

    while [ $i -lt $to_remove ];
    do
        line=$( head -$i $filename | tail -n1 | cut -d'.' -f2- );
        printf "$i.$line\\n" >> $filename_temp;
        i=$(( i + 1 ));
    done

    if [[ -n $remove_till ]];
    then
        correct_number_checking $remove_till;
        if [ $remove_till -lt $to_remove ];
        then
            printf "The first argument must be smaller than the second argument.\\n";
            exit 1;
        fi
            i=$remove_till;
    fi

    while [ $i -ne "$line_count" ];
    do
        if [[ -n $remove_till ]];
        then
            index=$(( i - remove_till + to_remove ));
        else
            index=$i;
        fi
        i=$(( i + 1 ));
        line=$( head -$i $filename | tail -n1 | cut -d'.' -f2- );
        printf "$index.$line\\n" >> $filename_temp;
    done

    rm $filename;
    mv $filename_temp $filename;
}

# edit() edits chosen note.
# 1) Check $to_edit to be correct argument
# 2) Create temporary file
# 3) Coprying the lines from original to temporary file
#    through iteration (from the first to the line before line
#    that must be edited).
# 4) Insert new line instead of old one.
# 5) Continue copying lines from the new point.
#    The new point is line after $to_edit.
# 5) Delete original file, rename temporary file as the original.


edit()
{
    to_edit=$1;
    note="$2";
    correct_number_checking $to_edit;

    if [[ -z $note ]];
    then
        printf "The note must be non-empty.\\n";
        exit 1;
    fi

    touch $filename_temp;

    i=1;


    while [ $i -lt $to_edit ];
    do
        line=$( head -$i $filename | tail -n1 | cut -d'.' -f2- );
        printf "$i.$line\\n" >> $filename_temp;
        i=$(( i + 1 ));
    done

    color=$( head -$to_edit $filename | tail -n1 | cut -d'.' -f2 | cut -d'm' -f1 );
    m='m';
    edited_note="$to_edit.$color$m$note$white\\n";

    printf "$edited_note" >> $filename_temp;

    while [ $i -ne "$line_count" ];
    do
        i=$(( i + 1 ));
        line=$( head -$i $filename | tail -n1 | cut -d'.' -f2- );
        printf "$i.$line\\n" >> $filename_temp;
    done

    rm $filename;
    mv $filename_temp $filename;
}

# check_options_overflow() ensures that no odd arguments
# are entered.

check_options_overflow()
{
    if [[ -n $1 ]];
    then
        printf "Too much arguments!\\n";
        exit 1;
    fi
}

# make_backup() creates a copy of original file and
# locates it in @/local_notes_backup.
# If @/local_notes_backup already exists, the prompt
# requests a user to confirm rewriting existing backup.

make_backup()
{
    if [[ -f $filename_backup ]];
    then
        printf "Backup already exists.\\n";
        read -p "Do you want to rewrite the backup? [Y/n] " -r;
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            cp $filename $filename_backup;
            printf "Success.\\n"
        fi
    else
        cp $filename $filename_backup;
    fi
}

# restore_notes() rewrites original file with copy
# of backup file.
# But the function does it only in the case of existing
# backup file.

restore_notes()
{
    if ! [[ -f $filename_backup ]];
    then
        printf "No backup file.\\n";
    else
        read -p "Do you want to rewrite the notes from backup? [Y/n] " -r;
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            cp $filename_backup $filename;
            printf "Success.\\n"
        fi
    fi
}

# remove_files() is the helping function for
# uninstall() function.
# remove_files() removes all the files in the @ directory.

remove_files()
{
    rm -r ~/.notebook_files
}

# three_dots() is the helping function for
# uninstall() function.
# Just an animation for "thinking" effect.

three_dots()
{
    for (( i=0; i < 3; i++ ));
    do
        sleep 1;
        printf ".";
    done;
    sleep 1;
    printf "\\n"
}

# print_ok() is the helping function for
# uninstall() function.
# Prints out "OK" status systemd-style
# string.

print_ok()
{
    sleep 0.1;
    o="OK";
    printf "$bold[  $green$o$white$bold  ] ";
}

# print_failed() is the helping function for
# uninstall() function
# Prints out "FAILED" status systemd-style
# string.

print_failed()
{
    sleep 0.1;
    f="FAILED";
    printf "$bold[$red$f$white$bold] ";
}

# uninstall() deletes all the files.
# It helps to prepare before the uninstallation of
# notebook package.
#
# NOTE: in order to have fun, but not loose the notes,
# copy ~/.local_notes and ~/.local_notes_backup into
# some other place.

uninstall()
{
    read -p "Do you want to delete all the files? [Y/n] " -r;
    if [[ $REPLY =~ ^[Yy]$ ]];
    then
        printf "Hm";
        three_dots;
        read -p "Are you sure? [Y/n] " -r;
        if [[ $REPLY =~ ^[Yy]$ ]];
        then
            printf "Well";
            three_dots;
            read -p "Are you completely sure? [Y/n] " -r;
            if [[ $REPLY =~ ^[Yy]$ ]];
            then
                printf "Preparing to uninstall";
                three_dots;
                sleep 1.5;
                clear;
                print_ok;
                printf "Unexpectedly loaded daemon systemd.\\n";
                sleep 0.1;
                printf "\\t Lennart Poettering, WTF?\\n";
                print_ok;
                printf "Sent 'WTF' to Lennart Poettering.\\n";
                print_ok;
                printf "Started pretending doing something useful.\\n";
                sleep 0.1;
                printf "\\t Plugging microwave to USB4...\\n";
                print_failed;
                printf "Failed to plug microwave.\\n";
                print_ok;
                printf "Sent user's nudes to a random girl.\\n";
                sleep 1;
                print_ok;
                printf "Loaded Minecraft with shaders in order to heat the room.\\n";
                remove_files;
                print_ok;
                printf "Removed necessary files (at this point).\\n";
                print_ok;
                printf "Made Lenin and Stalin alive.\\n";
                print_ok;
                printf "Recreated USSR.\\n";
                print_ok;
                printf "Changed file permissions to accessible for everyone except capitalists.\\n";
                print_ok;
                printf "Checked e-mail for the viruses.\\n";
                print_ok;
                printf "Invented the vaccine against AIDS.\\n";
                print_ok;
                printf "Installed Backbone.js framework.\\n";
                sleep 0.1;
                printf "\\t Trying to create good project using Backbone.js...\\n";
                print_failed;
                printf "Failed to create good project.\\n";
                print_ok;
                printf "Uninstalled Backbone.js framework.\\n";
                print_ok;
                printf "Congratulated user's grandmother on 'Still alive today.'\\n";
                print_ok;
                printf "Promised user's mother to visit her again.\\n";
                print_ok;
                printf "Stopped to pretend doing useful actions.\\n";
                print_ok;
                printf "Stopped to scare user with systemd-style messages.\\n";
                sleep 2;
            fi
        fi
    else
        phrase1="The files have been corrupted. MW-HA-HA!";
        phrase2="Backup file won't help you.";
        printf "1. $green$bold$phrase1$white\\n" > $filename;
        printf "1. $green$bold$phrase2$white\\n" > $filename_backup;
        printf "OK\\n";
    fi
}

# Autodetection of the terminal emulator.
# NOTE: it's difficult to provide initial command loading
# for terminal emulators, such as:
# Guake.

choose_terminal()
{
    terms=(alacritty gnome-terminal lxterminal xterm terminator rxvt Eterm termit xfce4-terminal tilda);
    for t in ${terms[*]};
    do
        if [ "$(command -v "$t")" ];
        then
            terminal=$t;
            break;
        fi
    done
}

# schedule() schedules notebook loading, provided by at utility.
# Works in this way:
# - chooses one terminal of available to print out notes contents;
# - creates script to load terminal with initial commands.
# NOTE: at uses /bin/sh to load script.
# - prompt to read time to schedule;
# - schedule loading using at.
# In the case of fail (incorrect date), remove the script.

schedule()
{
    if ! [ "$(command -v at)" ];
    then
        printf "This feature requires$green$bold at$white utility.\\n";
        exit 1;
    elif [[ -z $terminal ]];
    then
        choose_terminal;
    fi

    launcher=;

    case $terminal in

        'alacritty')
            launcher='alacritty --hold --command notebook'
            ;;
        'gnome-terminal')
            launcher='gnome-terminal -- bash -c "notebook; sleep 1000000"';
            ;;
        'lxterminal')
            launcher='lxterminal --command "notebook; sleep 1000000"';
            ;;
        'xterm' | 'terminator')
            launcher="$terminal -e 'notebook; sleep 1000000'";
            ;;
        'rxvt' | 'Eterm' | 'termit')
            launcher="$terminal -e bash -c 'notebook; sleep 1000000'";
            ;;
        'xfce4-terminal')
            launcher='xfce4-terminal -e \"bash -c \\\"notebook; sleep 1000000\\\"\"';
            ;;
        'tilda')
            launcher='tilda -c \"bash -c \\\"notebook; sleep 1000000\\\"\"';
            ;;
        '')
            printf "No terminal is detected.\\n";
            exit 1;
            ;;
        *)
            printf "For $terminal scheduling feature isn't provided yet.\\n";
            exit 1;
            ;;

    esac

    sch_number=$( find ~/.notebook_files -maxdepth 1 -name "sch*" | wc -l );
    sch_name="scheduled_commands$sch_number.sh";

    while [[ -n $( find ~/.notebook_files -maxdepth 1 -name "$sch_name" ) ]];
    do
        sch_number=$(( sch_number + 1 ));
        sch_name="scheduled_commands$sch_number.sh";
    done

    touch ~/.notebook_files/$sch_name;
    printf "#!/bin/sh
export DISPLAY=$DISPLAY;
$launcher;
rm ~/.notebook_files/$sch_name;\\n" > ~/.notebook_files/$sch_name;
    chmod +x ~/.notebook_files/$sch_name;

    printf "Print time to schedule using$green$bold at$white utility format\\n> ";
    read -r;
    at -f ~/.notebook_files/$sch_name "$REPLY" || rm ~/.notebook_files/$sch_name;
}

# usage() is the --help section.

usage()
{
printf 'Usage: notebook [OPTION] [VALUE]
Take notes inside the terminal.\n
    -a, --add\t\tAdd note VALUE.
    -p, --paint\t\tSet color VALUE.
               \t\tUse only after -a, for instance:\n
    $ notebook -a "foo" -p "green"\n
    -e, --edit\t\tReplace the note number VALUE with another.
              \t\tFor example:\n
    $ notebook -e 3 "New note"\n
    -c, --clear\t\tClear all the notes.
    -r, --remove\tRemove the line number VALUE.
                \tAlso you can set the interval:\n
    $ notebook -r VALUE1 VALUE2\n
    -b, --backup\tMake a backup.
    -rs, --restore\tRestore notes from backup.
    -sch, --schedule\tSchedule loading notebook for later,
                    \tusing at utility format.
                    \tVALUE is your prefered terminal emulator.
    --uninstall\t\tDelete all files before the uninstall.
               \t\tBe careful.
    -h, --help\t\tShow the help.\n
With no parameters, notebook shows saved notes.\n';
}


##### Main


# I think, Main section is understandable and
# doesn't need any explainations.
#
# Just remember that "shift" deleted $1 and moves the script
# arguments:
# $2 -> $1
# $3 -> $2
# ...
# $n -> $n-1

case $1 in

    '-a' | '--add')
        shift;
        note="$1";
        if [[ $2 == '-p' || $2 == '--paint' ]];
        then
            shift;
            shift;
            choose_color $1;
        fi
        check_options_overflow $2;
        write_notes "$note";
        ;;

    '-r' | '--remove')
        shift;
        check_options_overflow $3;
        remove_line $1 $2;
        ;;
        
    '-e' | '--edit')
        shift;
        check_options_overflow $3;
        edit $1 "$2";
        ;;

    '-b' | '--backup')
        check_options_overflow $2;
        make_backup;
        ;;

    '-rs' | '--restore')
        check_options_overflow $2;
        restore_notes;
        ;;

    '-c' | '--clear')
        check_options_overflow $2;
        clear_notes;
        ;;

    '--uninstall')
        check_options_overflow $2;
        uninstall;
        ;;

    '-h' | '--help')
        check_options_overflow $2;
        usage;
        ;;

    '-sch' | '--schedule')
        shift;
        terminal=$1;
        check_options_overflow $2;
        schedule;
        ;;

    '')
        show_notes;
        ;;

    *)
        usage;
        ;;

esac



##### End?
